challenge 7
Manel0712/Javascript-callbacks pull request #1
Opened 2023-12-05 18:48 UTC by Manel0712

2023-12-10 17:24 UTC, tictools requested changes

2023-12-10 17:24 UTC, tictools commented on exercise_01/transformStringToCollection.js
> +const transformStringToArray = function (value, onError, onSuccess) {
Validations and error handling must be managed as first case.

It's not necessary creating a constant for this. You can directly invoke callback and return its value

```suggestion
const transformStringToArray = function (value, onError, onSuccess) {
  if (typeof value !== "string" && value === "") {
    return onError();
  }
  return onSuccess(value);
};
```

FIX: apply validation and error handling as first step

2023-12-10 17:24 UTC, tictools commented on exercise_02/createUser.js
> +const createUser = function (email, onError, onSuccess) {
Take a look at comment in exercice `transformStringToArray.js`

FIX: apply validation and error handling as first step

2023-12-18 18:33 UTC, GALLEGOOOO approved these changes

2024-01-07 10:28 UTC, tictools approved these changes

2024-01-07 10:30 UTC, merged